- name: Install packages
  hosts: all
  vars:
    components:
      - nginx
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name: "{{ components }}"
        state: present
